service: lambda-thumbnail-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  timeout: 5
  memorySize: 512
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self.provider.region}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

custom:
  bucket: image-thumbnail
  pythonRequirements:
    dockerizePip: true


functions:
  s3-thumbnail-generator:
    handler: handler.thumbnail_generator
    events:
      - s3:
          bucket: image-thumbnail
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

plugins:
  - serverless-python-requirements